// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpkmes90PEJrJB8zCtQVe0p93FDExXZbA',
    appId: '1:967324931485:web:5490d0a3bf5a56a8c00b74',
    messagingSenderId: '967324931485',
    projectId: 'fir-flutter-6f56f',
    authDomain: 'fir-flutter-6f56f.firebaseapp.com',
    storageBucket: 'fir-flutter-6f56f.appspot.com',
    measurementId: 'G-5L6P3LXP77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-JSKJGQDByXKPZ4kIHq8xiu2K2o1pB0g',
    appId: '1:967324931485:android:db95834ae717cfa8c00b74',
    messagingSenderId: '967324931485',
    projectId: 'fir-flutter-6f56f',
    storageBucket: 'fir-flutter-6f56f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbfMQ7SwavbR1LxTaCTZBT18znNVd1IZc',
    appId: '1:967324931485:ios:768e8431cb86211ac00b74',
    messagingSenderId: '967324931485',
    projectId: 'fir-flutter-6f56f',
    storageBucket: 'fir-flutter-6f56f.appspot.com',
    iosBundleId: 'com.example.whatsappking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbfMQ7SwavbR1LxTaCTZBT18znNVd1IZc',
    appId: '1:967324931485:ios:768e8431cb86211ac00b74',
    messagingSenderId: '967324931485',
    projectId: 'fir-flutter-6f56f',
    storageBucket: 'fir-flutter-6f56f.appspot.com',
    iosBundleId: 'com.example.whatsappking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpkmes90PEJrJB8zCtQVe0p93FDExXZbA',
    appId: '1:967324931485:web:f16f8d48488b9984c00b74',
    messagingSenderId: '967324931485',
    projectId: 'fir-flutter-6f56f',
    authDomain: 'fir-flutter-6f56f.firebaseapp.com',
    storageBucket: 'fir-flutter-6f56f.appspot.com',
    measurementId: 'G-2PGZWP1PBZ',
  );

}